version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
