version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - grpc-network
    command: python -v server.py  # This runs the script with verbose output
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    networks:
      - grpc-network
networks:
  grpc-network:
    driver: bridge