# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrape.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscrape.proto\x12\x0bHtmlScraper\"/\n\x07Request\x12\x11\n\thtml_text\x18\x01 \x01(\t\x12\x11\n\tpage_type\x18\x02 \x01(\t\"-\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tjson_data\x18\x02 \x01(\t2I\n\x0bHtmlScraper\x12:\n\x0bProcessPage\x12\x14.HtmlScraper.Request\x1a\x15.HtmlScraper.ResponseB\x10Z\x0e./;HtmlScraperb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scrape_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016./;HtmlScraper'
  _globals['_REQUEST']._serialized_start=29
  _globals['_REQUEST']._serialized_end=76
  _globals['_RESPONSE']._serialized_start=78
  _globals['_RESPONSE']._serialized_end=123
  _globals['_HTMLSCRAPER']._serialized_start=125
  _globals['_HTMLSCRAPER']._serialized_end=198
# @@protoc_insertion_point(module_scope)
